### ISSUE TITLE
Cleanup attachments

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-cleanup#1]
From @fmonthel

Wekan-cleanup fix to delete (at least into cfs.attachments.filerecord) upload data.
Not sure how to proceed with other cfs.* collection, I need to look deeper
wekan-cleanup fix as well to delete checklists

Script is deleting as well board(s) with no cards into and created more than x days ago

**Comment by maulal** [comment]
Hi, i have already write a script in javascript that delete all orphans data in wekan (gridFS document also). I think it should be better to use javascript also to cleanup the databases (in the future it could be integrate easily in wekan with a "cron like" pluggin).

At least, it's easier to execute:

- No need to install a python driver
- the script work with the mongo shell only (it's often install with the databases)

For my purpose, i will do this script, so if it's needed i can share.

bye

**Comment by xet7** [comment]
@maulal 

Please submit pull request to this repo, that does:
- Create new directory named "Javascript"
- Add your Javascript cleanup script, license and readme to that Javascript directory
- If possible, use MIT license so your code is easier to integrate to Wekan.

Thanks!

**Comment by maulal** [comment]
@xet7 Done ! I will add soon another script, in the same idea as @fmonthel did, but in javascript.

bye
