### ISSUE TITLE
Script deletes template-container boards if empty

### ISSUE THREAD

**Issue by niklasdahlheimer** [wekan/wekan-cleanup#12]
After running the cleanup script on an docker instance of the newest wekan version (4.03.0), existing users can not access the template page ("page not found"). Further investigations showed that the template-container boards have been deleted and can not be recreated without manual hands-on on the db.

I'm not really into python and mongoDb syntax, but it looks like this part of the script is deleting all boards without cards
https://github.com/wekan/wekan-cleanup/blob/01dc052fba697a35a5cf50f1673ed8553d0d84a7/cleanup.py#L75

So boards with type "template-container" should be excluded here.

**Comment by xet7** [comment]
@niklasdahlheimer 

Please add pull request to comment out that, and add warning.
