### ISSUE TITLE
Username and Password

### ISSUE THREAD

**Issue by Sebastian-Juch** [wekan/wekan-cleanup#14]
Hi there i try to use the cleanup script but i cannot handle it. I'm using WEKAN in snap on  Ubuntu 18.04.4 LTS. I don't know the mongodb user or password to add this information to the script. I tried the admin user credential of WEKAN but without any positiv result! How to find the user credentials for mongodb in SNAP ? 

Best Regards

**Comment by lindhork** [comment]
Hi @Sebastian-Juch,
I believe that when installing wekan via snap, by default no admin is created for mongodb and authentication is not required either. With the cli tools from mongodb you can check if you can log in without a passowrt, just use `mongo --port 27019`. Then you can run e.g. `show dbs`, if you get an output showing all databases, you don't need a password to connect to mongodb.

**Comment by xet7** [comment]
Yes. MongoDB is accessible to localhost 127.0.0.1 without username and password. It's not accessible to Internet.

**Comment by mgiacomoli** [comment]
With my pull request you can use cleanup script without needing to authenticate, see #19
