### ISSUE TITLE
How to delete attachments properly ? 

### ISSUE THREAD

**Issue by fmonthel** [wekan/wekan-cleanup#4]
Question opened...
I deleted in attachements collection orphans entries but I think we need to delete in another place
@xet7 : your help is appreciated
Thanks

**Comment by xet7** [comment]
@fmonthel 

Please look at https://github.com/wekan/wekan/pull/875 so we could get attachment handling working better sometime.

**Comment by maulal** [comment]
You also can look at the javascript tools ;)

**Comment by fmonthel** [comment]
Managed into this PR https://github.com/wekan/wekan-cleanup/pull/5
