### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by supercrypt** [wekan/wekan-cleanup#6]
**Impacted version**: v0.72
**Server Setup Information**: Local VM

* Operating System: Debian 9
* Deployment Method(tar/sandstorm/snap/docker/etc /http frontend (nginx, httpd, ...)): Docker quay.io Image
* Node Version:  v.8.9.3
* MongoDB Version: 3.2.18
*Python 2.7.13
*python-pymongo 3.4.0-1

Hi, 

we have tested the script in our wekan installation but there will no data cleaned up.
I have set all the variables to 7 days. 

Here is the output from script:
[USERS] Checking users emails compliance (lowercase)...
[BOARDS] Deleting 0 archived board(s)....
[BOARDS] Checking boards with no card into....
[BOARDS] Checking deleted user into boards (userId not more in database)....
[LISTS] Deleting 0 archived list(s)....
[CARDS] Deleting 0 archived cards(s)....
[CARDS] Checking deleted user into cards (userId not more in database)....
[LISTS] Deleting 0 orphan list(s) (boardId = False)....
[LISTS] Checking orphan lists (boardId not more in database)....
[CARDS] Checking orphan cards (boardId or listId or userId not more in database)....
[CHECKLISTS] Checking orphan checklist (cardId or userId not more in database)....
[CARD_COMMENTS] Checking orphan card_comments (cardId or userId not more in database)....
[ATTACHMENTS] Checking orphan attachments (cardId or userId not more in database)....
[ATTACHMENT_FILES] Checking orphan attachment files (attachment not more in database)....
[ATTACHMENT_CHUNKS] Checking orphan attachment chunks (file_id not more in database)....
[ACTIVITIES] Checking orphan activities (cardId or userId or boardId or listId or oldListId or commentId not more in database)....

In Wekan i can see the archived boards which are older than 7 days too. (See attached screenshot)
![bugwekancleanup](https://user-images.githubusercontent.com/36037249/36200380-c56146f2-117c-11e8-84b0-3722d66b73ce.png)

I already tried to set the vars to lower values with same result.

**Comment by pwlgrzs** [comment]
I'm having the same issue, nothig's being cleaned up. I'm also running this in Docker, 0.79, port has been exposed.

**Comment by scoubidoo** [comment]
i don't understand why we used Admin database because it's not the database of wekan.. if i change the name of the database in the script.. i ve got error.
with admin no error but no cleaning .. can you help me.

Thx
