### ISSUE TITLE
cleanup.py deletes comments from cards

### ISSUE THREAD

**Issue by m1d1** [wekan/wekan-cleanup#7]
Do not use! 
Since Wekan v2.90 `cleanup.py` deletes comments from cards, identifying them as orphaned activity.
`[ACTIVITY] Deleting orphan activity xyz (listId not more in database)....`

**Comment by xet7** [comment]
@m1d1 

Please add PR to fix it.

**Comment by m1d1** [comment]
@xet7 What is PR?

**Comment by m1d1** [comment]
@xet7 I assume the problem is comming from Wekan not from the script.

Wekan should not set the `listId ` field to `null` in `activities` collection. 
```
db.activities.find({"userId":"YmMF6ee5hbbpueqBM", "activityType" : "addComment", "listId":null})

{ "_id" : "R5Ln7zAym2mRFSMgS", 
"userId" : "YmMF6ee5hbbpueqBM", "
activityType" : "addComment", 
"boardId" : "Ax9ksfWehQRt6riew", 
"cardId" : "PDoPM7MskvAShAdxu", 
"commentId" : "dGu2uw5wStCnhsBWT", 

"listId" : null, 

"swimlaneId" : null, 
"createdAt" : ISODate("2019-06-26T08:44:32.613Z") }
```
`cleanup.py` Line 181, delete trigger:
`elif 'listId' in activity and lists.count({"_id": activity['listId']}) == 0 :`
is trying to resolve the `listId` reference if set - and deletes the activity if not resolvable to `lists` collection. Null is not resolvable.
